# Generated by Django 4.0.2 on 2022-03-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_current_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='current_user',
            new_name='account',
        ),
    ]
